### PR TITLE
1.3.7

### LINKED ISSUE #108: Exception thrown when the add-on assigned to permission interface has been removed

### LINKED ISSUE #109: On XF 2.2.7+ when minifying JS files go with the stock minifier service

### LINKED ISSUE #111: [8.1] php cmd.php tck-devtools:build-readme $1 --markdown doesn't work
Attempting to run `php cmd.php tck-devtools:build-readme $1 --markdown` fails on PHP 8.1 as https://github.com/thephpleague/html-to-markdown isn't updated via the https://github.com/xprt64/php-markdown-table-converter dependency.

### PR DESCRIPTION
**Pull request by ticktackk**

### CODE REVIEW

File: Cli/Command/ClassExtension.php [hunk 1]
```diff
@@ -11,7 +11,7 @@
 use Symfony\Component\Console\Question\Question;
 use XF\Util\File;
 use XF\AddOn\AddOn;
-use function dirname;
+const USE_FUNCTION_PLACEHOLDER = true;
```
Comment (Xon) [inline Cli/Command/ClassExtension.php:14]: Might want to remove this as otherwise some php versions will break
